name: cs7643-finalproject
channels:
  - defaults
  - pytorch
dependencies:
  # - meshio # will need to install afterwards with `conda install -c conda-forge meshio`
  - matplotlib
  - numpy
  - pytorch
  - tqdm
  - matplotlib
  - pip
  - pip:
    - plyfile
    - torch-geometric